version: "3"
services:
  # app:
  #   image: mysql-connectivity:latest
  #   links:
  #     - db
  #   ports:
  #     - "5000:5000"
  db:
    image: mysql/mysql-server:latest
    ports:
      - "3200:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: someshDB
      MYSQL_USER: somesh
      MYSQL_PASSWORD: someshPass
    volumes:
      - ./db1:/docker-entrypoint-initdb.d/:ro